### ISSUE TITLE
Add repo to packagist.org

### ISSUE THREAD

**Issue by jsteggink** [jsteggink/solarium-cloud#1]
I'd like to add this repo to packagist. However, only the owner of the vendor 'solarium' can do this. It would be great to add the packagist API to the webhooks of this repo.

**Comment by basdenooijer** [comment]
I've added the repo to packagist, however there is an issue with the composer file:

The solarium/solarium-cloud package of which you are a maintainer has
failed to update due to invalid data contained in your composer.json.
Please address this as soon as possible since the package stopped updating.

It is recommended that you use `composer validate` to check for errors when you
change your composer.json.

Below is the full update log which should highlight errors as
"Skipped branch ...":

[Composer\Repository\InvalidRepositoryException]: Some branches contained invalid data and were discarded, it is advised to review the log and fix any issues present in branches

Reading composer.json of solarium/solarium-cloud (0.1.1)
Importing tag 0.1.1 (0.1.1.0)
Reading composer.json of solarium/solarium-cloud (0.1.0)
Importing tag 0.1.0 (0.1.0.0)
Reading composer.json of solarium/solarium-cloud (develop)
Importing branch develop (dev-develop)
Skipped branch develop, Invalid package information:
require.php : invalid version constraint (Could not parse version constraint ~: Invalid version string "~")

Reading composer.json of solarium/solarium-cloud (master)
Importing branch master (dev-master)

**Comment by jsteggink** [comment]
Thanks Bas, I have fixed the error.
